language: node_js
node_js:
  - "stable"
script: npm run test
deploy:
  provider: npm
  email: sparrow.jang@gmail.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: A/V1xsaKNTTNWVg/RIITgAyPDfwO43C5gXmJjmLuphblBvrglKi8gtqHJduOLPTKnCucZ/ha9X+xSmO/KmclojcE0U+0g9l64d+J39VlYIdv1t/7/Rkn6jt7Y9NIfI8OO2lVWUSsdPtdwTTFqKz86CI1dluzhS2cUr332lfHu1+UgTYdLZ9Z0HoQzsAgJuJzlhdgxX6iVryH5JyI7MHX3Ia6Hzo5HPNCZ03N5l7os9rrbbFYmX3ilkFCG5AwnPoYBwGOGT2NT7UkvtHwwHo1HgIH3Uf0Fd59SxhfR4cJFfJHTgPXUYtNEWbQwlcAoYpK3mZ6rbkjsda1ZwakDXV+pwf3lc8zxd5AaLAGLsdfpV2Ob+lA35f0cHZPxoETouR/Sl1kAcIlBDCCXewgty3xtKyfT1odY0KQVQPyb75z2Vnq51J9gUkgg4gp4FiRXCTw+QBUwk8FcofkR/HrqPmTs3IO6xWiU9/VxqWe3zULqQueBpuX1QHrEh3cYVfc+/lxNvRc3xbJ8vDe1CfRml+DmSxIzwd2en18Va7eonClfyGF/V+rhdFtI/DKVuV2KfRkZbuAKgZ9m1FFiWIqONvjo4ciI+adbjhsHCW6xO0pcEEPi3GwBNX0uB3OKbFs6exIN6vrJx7Pyc18ciWLHLbHsn9jYvvBLIQmrFzs8zZo6NM=
