language: node_js
node_js: '8'
deploy:
  provider: npm
  email: sparrow.jang@gmail.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: CYKpes/znhRWQfiy/yZPqflpxAxbLWrMLENgLqOuFAAWoZJWkmQV1aFfE2lJDDjezv1/z6byJowoTv+VZ/Js6DJBiqeEeIpMXpeGyoMQ77ir7bYI9emVJ6cNnqlyyibR9DmIf13rMOG67Y3vlE7iyROcTdqAPbClKxFJJoP2W9pbd1UDF8zhDTD86wTQEa3h8Tc8XixzSvYzGTqO3ZyiMj7DpNrYeX3O7pKFp4HUZMJursygOD8CbMqmkXaQzoYxUYImj2nsWYk9QI1ZYjE9yx9KJpiSYmIfGFtXz6QAMreYEUlVBX6pviprw+Jp9Ka5FRzbKK5QpM92CLmAc6YO/xjMhKBiu0SpJ3x4Jgr/JhBi8ORkmv+66s3RR2Dt9imIXBT07Gkwv9QZG53rVtdvAgw5B3GZ9AfPSqaAqXhDF7toAlcxIXsM4DyvXIXhuNWyQCrZ9yBCnoP6S1yabZfipz7vrTEYsRgVcagIO0RMArApBhfDZpxqesSpqJmGzQxX1CN+v2l1AynA1eVB/dgDCVO9aIqRGpMIFY/CorOsR6eFDCxxXCBd9YVdk0SVgoJKy0zhdwu8TWwNk204JDFnAO1WpDyxk+veAYgr94V7fHEGdjoAe2/YBr9qW1GNQeZHFlpMcjYww6Zyz8vZQyL8bUXeufU1nf4Sb02iO2gz+IU=

